# Generated by Django 3.2.13 on 2022-05-17 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('dateCommissioned', models.DateField()),
                ('starsRating', models.IntegerField()),
                ('account_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BuildingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rate', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('building_category', models.PositiveSmallIntegerField(choices=[(1, 'single_rooms'), (2, 'bed_sitters'), (3, 'one_bedrooms'), (4, 'two_bedrooms'), (5, 'three_bedrooms'), (6, 'four_bedrooms'), (7, 'mansion')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cover', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_images', to='BuildingsAPI_Buildings.building')),
            ],
        ),
    ]
