# Generated by Django 3.2.13 on 2022-05-17 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BuildingsAPI_Users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BuildingsAPI_Buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_building', to='BuildingsAPI_Users.imageupload'),
        ),
        migrations.AddField(
            model_name='buildingcomment',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_comments', to='BuildingsAPI_Buildings.building'),
        ),
        migrations.AddField(
            model_name='buildingcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='building',
            name='careTaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_caretaker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='building',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryOf_building', to='BuildingsAPI_Buildings.category'),
        ),
        migrations.AddField(
            model_name='building',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
