# Generated by Django 3.2.13 on 2022-05-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuildingsAPI_Buildings', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='category',
            new_name='building_category',
        ),
    ]
